=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/schemas/get-controlled-gmrs-for-departure-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "#/get-controlled-gmrs-departure",
  "type": "array",
  "items": {
    "$id": "#/get-controlled-gmrs-departure/items",
    "type": "object",
    "additionalItems": true,
    "required": [
      "gmrId",
      "isUnaccompanied",
      "checkedInCrossing"
    ],
    "anyOf": [
      { "required": [ "vehicleRegNum" ] },
      { "required": [ "trailerRegistrationNums" ] },
      { "required": [ "containerReferenceNums" ] }
    ],
    "properties": {
      "gmrId": { "$ref": "gmr-types-schema.json#/definitions/gmrId" },
      "isUnaccompanied": { "$ref": "gmr-types-schema.json#/definitions/isUnaccompanied" },
      "reportToLocations": { "$ref": "gmr-types-schema.json#/definitions/reportToLocations" },
      "vehicleRegNum": { "$ref": "gmr-types-schema.json#/definitions/vehicleRegNum" },
      "trailerRegistrationNums": { "$ref": "gmr-types-schema.json#/definitions/trailerRegistrationNums" },
      "containerReferenceNums": { "$ref": "gmr-types-schema.json#/definitions/containerReferenceNums" },
      "checkedInCrossing": { "$ref": "gmr-types-schema.json#/definitions/checkedInCrossing" }
    }
  }
}

=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/examples/get-controlled-gmrs-for-departure-example.json
[
  {
    "gmrId": "GMRB00000GKW",
    "isUnaccompanied": false,
    "vehicleRegNum": "PJ15 JEF",
    "checkedInCrossing": {
      "routeId": "103",
      "localDateTimeOfArrival": "2021-06-05T09:20"
    }
  },
  {
    "gmrId": "GMRB0001IFM5",
    "isUnaccompanied": true,
    "vehicleRegNum": "GU62 SJE",
    "trailerRegistrationNums": ["AB29 3824"],
    "checkedInCrossing": {
      "routeId": "103",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  },
  {
    "gmrId": "GMRB0001IFM5",
    "isUnaccompanied": true,
    "vehicleRegNum": "GU62 SJE",
    "containerReferenceNums": ["GB2 93824"],
    "checkedInCrossing": {
      "routeId": "104",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  },
  {
    "gmrId": "GMRB0001IFM5",
    "isUnaccompanied": true,
    "vehicleRegNum": "GU62 SJE",
    "trailerRegistrationNums": ["AB 293824"],
    "containerReferenceNums":  ["GB 293824"],
    "checkedInCrossing": {
      "routeId": "105",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  }
]
