=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/schemas/get-checked-in-gmrs-for-departure-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "#/get-checked-in-gmrs-departure",
  "type": "array",
  "items": {
    "$id": "#/get-checked-in-gmrs-departure/items",
    "type": "object",
    "additionalItems": true,
    "required": [
      "gmrId",
      "updatedDateTime",
      "isUnaccompanied",
      "checkedInCrossing"
    ],
    "anyOf": [
      { "required": [ "vehicleRegNum" ] },
      { "required": [ "trailerRegistrationNums" ] },
      { "required": [ "containerReferenceNums" ] }
    ],
    "properties": {
      "gmrId": { "$ref": "gmr-types-schema.json#/definitions/gmrId" },
      "updatedDateTime": { "$ref": "gmr-types-schema.json#/definitions/updatedDateTime" },
      "isUnaccompanied": { "$ref": "gmr-types-schema.json#/definitions/isUnaccompanied" },
      "reportToLocations": { "$ref": "gmr-types-schema.json#/definitions/reportToLocations" },
      "vehicleRegNum": { "$ref": "gmr-types-schema.json#/definitions/vehicleRegNum" },
      "trailerRegistrationNums": { "$ref": "gmr-types-schema.json#/definitions/trailerRegistrationNums" },
      "containerReferenceNums": { "$ref": "gmr-types-schema.json#/definitions/containerReferenceNums" },
      "checkedInCrossing": { "$ref": "gmr-types-schema.json#/definitions/checkedInCrossing" },
      "inspectionRequired": { "$ref": "gmr-types-schema.json#/definitions/inspectionRequired" },
      "readyToEmbark": { "$ref": "gmr-types-schema.json#/definitions/readyToEmbark" }
    }
  }
}

=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/examples/get-checked-in-gmrs-for-departure.json
[
  {
    "gmrId": "GMRB00000GKW",
    "updatedDateTime": "2021-06-05T04:21:23.492Z",
    "isUnaccompanied": false,
    "vehicleRegNum": "PJ15 JEF",
    "checkedInCrossing": {
      "routeId": "103",
      "localDateTimeOfArrival": "2021-06-05T09:20"
    },
    "inspectionRequired": true,
    "reportToLocations": [
    {
      "inspectionTypeId": "1",
      "locationIds": [
        "L0029A", "L0030A", "L0031A"
      ]
    },
    {
      "inspectionTypeId": "2",
      "locationIds": [
        "L0029A", "L0031A"
      ]
    }
  ]
  },
  {
    "gmrId": "GMRB0001IFM5",
    "updatedDateTime": "2021-06-05T04:20:02.284Z",
    "isUnaccompanied": false,
    "vehicleRegNum": "GU62 SJE",
    "checkedInCrossing": {
      "routeId": "104",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    },
    "readyToEmbark": true,
    "inspectionRequired": false
  },
  {
    "gmrId": "GMRB0001EKG2",
    "updatedDateTime": "2021-06-05T04:17:48.406Z",
    "isUnaccompanied": true,
    "trailerRegistrationNums": ["AB29 3824", "SJ25 9382"],
    "checkedInCrossing": {
      "routeId": "104",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  },
  {
    "gmrId": "GMRB0002MD3K",
    "updatedDateTime": "2021-06-05T04:15:35.009Z",
    "isUnaccompanied": true,
    "containerReferenceNums":  ["GB 293824"],
    "checkedInCrossing": {
      "routeId": "105",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  }
]
