=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/schemas/get-controlled-gmrs-for-arrival-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "#/get-controlled-gmrs-arrival",
  "type": "array",
  "items": {
    "$id": "#/get-controlled-gmrs-arrival/items",
    "type": "object",
    "additionalItems": false,
    "required": [
      "gmrId",
      "isUnaccompanied",
      "actualCrossing"
    ],
    "anyOf": [
      { "required": [ "vehicleRegNum" ] },
      { "required": [ "trailerRegistrationNums" ] },
      { "required": [ "containerReferenceNums" ] }
    ],
    "properties": {
      "gmrId": { "$ref": "gmr-types-schema.json#/definitions/gmrId" },
      "isUnaccompanied": { "$ref": "gmr-types-schema.json#/definitions/isUnaccompanied" },
      "reportToLocations": { "$ref": "gmr-types-schema.json#/definitions/reportToLocations" },
      "vehicleRegNum": { "$ref": "gmr-types-schema.json#/definitions/vehicleRegNum" },
      "trailerRegistrationNums": { "$ref": "gmr-types-schema.json#/definitions/trailerRegistrationNums" },
      "containerReferenceNums": { "$ref": "gmr-types-schema.json#/definitions/containerReferenceNums" },
      "actualCrossing": { "$ref": "gmr-types-schema.json#/definitions/actualCrossing" }
    }
  }
}

=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/examples/get-controlled-gmrs-for-arrival-example.json
[
  {
    "gmrId": "GMRA0000028D",
    "isUnaccompanied": false,
    "vehicleRegNum": "KL58 FEM",
    "reportToLocations": [
      {
        "inspectionTypeId": "1",
        "locationIds": [
          "L0029A"
        ]
      }
    ],
    "actualCrossing": {
      "routeId": "107",
      "localDateTimeOfArrival": "2021-06-05T09:20"
    }
  },
  {
    "gmrId": "GMRA00009JR8",
    "isUnaccompanied": true,
    "trailerRegistrationNums": ["FB283721"],
    "reportToLocations": [
      {
        "inspectionTypeId": "1",
        "locationIds": [
          "L0029A"
        ]
      }
    ],
    "actualCrossing": {
      "routeId": "107",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  },
  {
    "gmrId": "GMRA00009JR8",
    "isUnaccompanied": true,
    "containerReferenceNums": ["GB283721"],
    "reportToLocations": [
      {
        "inspectionTypeId": "1",
        "locationIds": [
          "L0029A"
        ]
      }
    ],
    "actualCrossing": {
      "routeId": "107",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  },
  {
    "gmrId": "GMRA00009JR8",
    "isUnaccompanied": true,
    "trailerRegistrationNums": ["FB283721"],
    "containerReferenceNums":  ["GB283721"],
    "reportToLocations": [
      {
        "inspectionTypeId": "1",
        "locationIds": [
          "L0029A"
        ]
      }
    ],
    "actualCrossing": {
      "routeId": "19",
      "localDateTimeOfArrival": "2021-06-11T11:03"
    }
  }
]
