=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/schemas/get-reference-data.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "referenceData v1.15",
  "description": "reference Data for GVMS v1.15",
  "type": "object",
  "properties": {
    "routes": {
      "description": "The routes covered by GVMS",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "routeId": {
            "description": "The route identifier",
            "type": "string"
          },
          "routeDirection": {
            "description": "The direction of the route",
            "type": "string",
            "enum": [
              "UK_INBOUND",
              "UK_OUTBOUND",
              "GB_TO_NI",
              "NI_TO_GB"
            ]
          },
          "routeEffectiveFrom": {
            "description": "Date the route came into effect",
            "type": "string",
            "format": "date"
          },
          "departurePortId": {
            "description": "The id of the departure port",
            "type": "integer"
          },
          "arrivalPortId": {
            "description": "The id of the arrival port",
            "type": "integer"
          },
          "carrierId": {
            "description": "the id of the carrier operating that route",
            "type": "integer"
          },
          "routeEffectiveTo": {
            "description": "The date the route stopped being used",
            "type": "string",
            "format": "date"
          }
        },
        "required": [
          "routeId",
          "routeDirection",
          "routeEffectiveFrom",
          "departurePortId",
          "arrivalPortId",
          "carrierId"
        ]
      }
    },
    "ports": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "portId": {
            "description": "The id of the port",
            "type": "integer"
          },
          "portRegion": {
            "description": "The region the port is grouped into for CTC",
            "type": "string"
          },
          "portEffectiveFrom": {
            "description": "The date the port came into effect",
            "type": "string",
            "format": "date"
          },
          "portDescription": {
            "description": "Description of the port eg: the port's name",
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "timezoneId": {
            "description": "The UTC Identifier",
            "type": "string",
            "maxLength": 50
          },
          "chiefPortCode": {
            "description": "The port code specific to CHIEF",
            "type": "string"
          },
          "cdsPortCode": {
            "description": "The port code specific to CDS",
            "type": "string"
          },
          "officeOfTransitCustomsOfficeCode": {
            "description": "Customs office code for CTC",
            "type": "string",
            "minLength": 8,
            "maxLength": 8
          },
          "portEffectiveTo": {
            "description": "The date the port stopped being used",
            "type": "string",
            "format": "date"
          },
          "portCountryCode": {
            "description": "The Country code of the associated Port",
            "type": "string",
            "pattern": "^[A-Z]{2}$"
          },
          "isOperatingArrivedExportsProcess": {
            "description": "If true, indicates that this port is operating the arrived exports process and as such requires all customs export declarations to be pre-arrived prior to check-in.  If omitted or false, indicates that this port is operating the standard exports process.",
            "type": "boolean"
          }
        },
        "required": [
          "portId",
          "portEffectiveFrom",
          "portDescription",
          "officeOfTransitCustomsOfficeCode",
          "portCountryCode"
        ]
      }
    },
    "carriers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "carrierId": {
            "description": "The id of the carrier",
            "type": "integer"
          },
          "carrierName": {
            "description": "The name of the carrier",
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          },
          "countryCode": {
            "description": "The country code where the carrier is registered",
            "type": "string",
            "pattern": "^[A-Z]{2}$"
          }
        },
        "required": [
          "carrierId",
          "carrierName"
        ]
      }
    },
    "locations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "locationId": {
            "description": "The id of the inspection facility.",
            "type": "string"
          },
          "locationDescription": {
            "description": "The name of the inspection facility location.",
            "type": "string"
          },
          "address": {
            "description": "The address where the inspection facility is located.",
            "type": "object",
            "properties": {
              "lines": {
                "description": "The building name or number, and street name where the inspection facility is located.",
                "type": "array",
                "minItems": 1,
                "maxItems": 4,
                "items": {
                  "type": "string"
                }
              },
              "town": {
                "description": "The town where the inspection facility is located.",
                "type": "string"
              },
              "postcode": {
                "description": "The postcode where the inspection facility is located.",
                "type": "string"
              }
            },
            "required": [
              "lines",
              "postcode"
            ]
          },
          "locationType": {
            "description": "The type of inspection facility; either Inland Border Facility (IBF), Border Control Post (BCP) or a facility that carries out all inspection types (ALL).",
            "type": "string",
            "enum": [
              "IBF",
              "BCP",
              "ALL"
            ]
          },
          "supportedDirections": {
            "description": "The directions of travel supported by the location.",
            "type": "array",
            "minItems": 1,
            "maxItems": 4,
            "items": {
              "type": "string",
              "enum": [
                "UK_INBOUND",
                "UK_OUTBOUND",
                "GB_TO_NI",
                "NI_TO_GB"
              ]
            }
          },
          "locationEffectiveFrom": {
            "description": "The date the inspection facility location starts being used.",
            "type": "string",
            "format": "date"
          },
          "locationEffectiveTo": {
            "description": "The date the inspection facility location stops being used.",
            "type": "string",
            "format": "date"
          },
          "supportedInspectionTypeIds": {
            "description": "The list of inspectionTypeIds for the types of inspections carried out.",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "requiredInspectionLocations": {
            "description": "The list of portIds that the inspection facility supports.",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer"
            }
          }
        },
        "required": [
          "locationId",
          "locationDescription",
          "address",
          "locationType",
          "locationEffectiveFrom",
          "supportedDirections",
          "supportedInspectionTypeIds",
          "requiredInspectionLocations"
        ]
      }
    },
    "inspectionTypes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "inspectionTypeId": {
            "description": "The id of the type of inspection that needs to be performed on the vehicle.",
            "type": "string"
          },
          "description": {
            "description": "The category of the type of inspection that needs to be performed on the vehicle e.g. CUSTOMS, DEFRA or TRANSIT.",
            "type": "string"
          }
        },
        "required": [
          "inspectionTypeId",
          "description"
        ]
      }
    },
    "ruleFailures": {
      "description": "The list of business and other possible rule failures within a GMR",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ruleId": {
            "type": "string"
          },
          "ruleDescription": {
            "type": "string"
          }
        },
        "required": [
          "ruleId",
          "ruleDescription"
        ]
      }
    }
  }
}

=== hmrc/goods-movement-system-port-api/resources/public/api/conf/1.0/examples/get-reference-data-example.json
{
  "routes": [
    {
      "routeId": "102",
      "routeEffectiveFrom": "2020-01-01",
      "routeEffectiveTo": "2020-01-02",
      "departurePortId": 7014,
      "routeDirection": "UK_OUTBOUND",
      "arrivalPortId": 6085,
      "carrierId": 1
    },
    {
      "routeId": "103",
      "routeEffectiveFrom": "2020-01-01",
      "departurePortId": 7054,
      "routeDirection": "UK_OUTBOUND",
      "arrivalPortId": 1401,
      "carrierId": 2
    }
  ],
  "ports": [
    {
      "portId": 7050,
      "portRegion": "Scotland",
      "portEffectiveFrom": "2000-01-01",
      "portDescription": "Aberdeen",
      "chiefPortCode": "",
      "cdsPortCode": "ABDABDABD",
      "officeOfTransitCustomsOfficeCode": "UNKNOWN?",
      "timezoneId": "Europe/London",
      "portCountryCode": "GB"
    },
    {
      "portId": 1401,
      "portRegion": "",
      "portEffectiveFrom": "2000-01-01",
      "portDescription": "Calais",
      "chiefPortCode": "",
      "cdsPortCode": "",
      "officeOfTransitCustomsOfficeCode": "UNKNOWN?",
      "timezoneId": "Europe/Paris",
      "portCountryCode": "FR"
    }
  ],
  "carriers": [
    {
      "carrierId": 1,
      "carrierName": "Stena Line",
      "countryCode": "SE"
    },
    {
      "carrierId": 2,
      "carrierName": "DFDS Seaways",
      "countryCode": "DK"
    }
  ],
  "ruleFailures": [
    {
      "ruleId": "001_1",
      "ruleDescription": "This type of declaration cannot be used for this direction of travel."
    },
    {
      "ruleId": "001_3",
      "ruleDescription": "This type of declaration cannot be used in this GMR based on the Haulier type you selected. Check and try again."
    }
  ]
}

=== hmrc/goods-movement-system-port-api/test-resources/referencedata/test-gvms-reference-data.json
{
  "routes": [
    {
      "routeId": "4",
      "routeDirection": "UK_INBOUND",
      "routeEffectiveFrom": "2022-04-16",
      "departurePortId": 6,
      "arrivalPortId": 1,
      "carrierId": 10
    },
    {
      "routeId": "5",
      "routeDirection": "GB_TO_NI",
      "routeEffectiveFrom": "2020-04-16",
      "departurePortId": 20,
      "arrivalPortId": 5,
      "carrierId": 5
    },
    {
      "routeId": "7",
      "routeDirection": "NI_TO_GB",
      "routeEffectiveFrom": "2022-04-16",
      "departurePortId": 12,
      "arrivalPortId": 14,
      "carrierId": 1
    },
    {
      "routeId": "6",
      "routeDirection": "NI_TO_GB",
      "routeEffectiveFrom": "2020-04-16",
      "routeEffectiveTo": "2020-04-16",
      "departurePortId": 12,
      "arrivalPortId": 14,
      "carrierId": 1
    }
  ],
  "ports": [
    {
      "portId": 1,
      "portRegion": "SOUTH",
      "portEffectiveFrom": "2020-04-16",
      "portDescription": "HOLYHEAD",
      "chiefPortCode": "567N",
      "cdsPortCode": "XY891",
      "officeOfTransitCustomsOfficeCode": "aaaaaaaa",
      "portCountryCode": "GB"
    },
    {
      "portId": 2,
      "portRegion": "SOUTH",
      "portEffectiveFrom": "2022-04-16",
      "portDescription": "DOVER",
      "chiefPortCode": "123L",
      "cdsPortCode": "XY123",
      "officeOfTransitCustomsOfficeCode": "GB000024",
      "portCountryCode": "GB"
    },
    {
      "portId": 25,
      "portRegion": "SOUTH",
      "portEffectiveFrom": "2020-04-16",
      "portDescription": "DOVER",
      "chiefPortCode": "123L",
      "cdsPortCode": "XY124",
      "officeOfTransitCustomsOfficeCode": "GB000024",
      "portCountryCode": "GB"
    }
  ],
  "carriers": [
    {
      "carrierId": 1,
      "carrierName": "P&0"
    }
  ],
  "locations": [
    {
      "locationId": "1",
      "locationDescription": "BELFAST LOCATION 1",
      "address": {
        "lines": [
          "1 Shamrock Lane",
          "Waldo"
        ],
        "town": "Belfast",
        "postcode": "NI1 6JG"
      },
      "locationType": "BCP",
      "locationEffectiveFrom": "2022-04-16",
      "supportedDirections": ["UK_INBOUND"],
      "supportedInspectionTypeIds": [
        "1"
      ],
      "requiredInspectionLocations": [
        2
      ]
    },
    {
      "locationId": "2",
      "locationDescription": "PORTSMOUTH LOCATION 5",
      "address": {
        "lines": [
          "36 Maryrose Avenue",
          "Hampshire"
        ],
        "town": "Portsmouth",
        "postcode": "PO6 7QU"
      },
      "locationType": "BCP",
      "locationEffectiveFrom": "2022-04-16",
      "supportedDirections": ["UK_INBOUND"],
      "supportedInspectionTypeIds": [
        "1"
      ],
      "requiredInspectionLocations": [
        2
      ]
    }
  ],
  "inspectionTypes": [
    {
      "inspectionTypeId": "1",
      "description": "CUSTOMS"
    }
  ],
  "ruleFailures": [
    {
      "ruleId": "BR005",
      "ruleDescription": "A GMR can only be used in one crossing between two customs territiories"
    },
    {
      "ruleId": "BR011",
      "ruleDescription": "This Customs declaration cannot be in more than one GMR"
    }
  ]
}
